### PR TITLE
Break up configuration page into multiple pages.

### PR DESCRIPTION
**Pull request by neeleshpoli**
## Description
The advanced configuration page is very large now, due to a large amount of config options. The details for each config option is also very lacking. This PR aims to break up each section of config options into its own page and elaborate on each section more.

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Proxy page
- [x] Authentication Page
- [x] Compression Page
- [x] Resource Pack Page
- [x] Commands Page
- [x] RCON Page
- [x] PVP Page
- [x] Logging Page
- [x] Query Protocol Page
- [x] LAN Broadcast Page

### CODE REVIEW

**Comment by Commandcracker** [comment]
And add this for the sha1 in the Resource Pack Page

Windown in (PowerShell):
Get-FileHash "<file>" SHA1

linux:
sha1sum "<file>"

macOS:
shasum -a 1 "<file>"

**Comment by neeleshpoli** [comment]
Good idea, thank you!

**Comment by Snowiiii** [comment]
I wonder if it is may confusing having 2 pages for authentication. One on how authentication does work and how others can implement custom auth for Pumpkin. And one for the Config. But no idea how to Split them

**Comment by Snowiiii** [comment]
Looks good. Great Job @neeleshpoli :+1:

**Pull request merged**
