### PR TITLE
allow assets for docker build

### PR DESCRIPTION
**Pull request by ThePaulo1**
Fix failing build due to assets not found

### CODE REVIEW

**Comment by Snowiiii** [comment]
Hey @ThePaulo1. Looks like this has something to do with docker, You should proberbly mention that the PR. Im not that fimilar with with Docker, The only "asset" we really have is the icon, Which is also Optional. Can you maybe explain what the issue is here?

**Comment by Snowiiii** [comment]
Ah i see. So when assets are included everything works fine?

**Comment by ThePaulo1** [comment]
yes the docker build succeeds when assest are included

**Comment by Snowiiii** [comment]
Great. Then thanks foe the PR @ThePaulo1 👍

**Pull request merged**
