### PR TITLE
workflows: begin work on docker image deployment

### LINKED ISSUE #125: Host docker build on a Container Registry
- [x] I've searched existing issues and couldn't find a duplicate.

**Is your feature request related to a problem? Please describe.**
Using a docker image for deployment requires downloading the source code and building the image from there

**Describe the solution you'd like**
I woud like the docker builds to be published to the Github Container Registry, or any container registry by adding a github actions workflow

### PR DESCRIPTION
**Pull request by lokka30**
## Description

Started work on `docker.yml` for automatic docker image deployment on pushes to to branches (notably, excluding people's PRs). Aims to resolve #125.

Somewhat in the brainstorming and testing stages at the moment, lots of things here aren't final, e.g., what container registry is being selected.

## Testing
A description of the tests performed to verify the changes:
- [x] N/A

## Checklist
Things need to be done before this Pull Request can be merged.
- [x] @Snowiiii advice [here](https://github.com/Snowiiii/Pumpkin/issues/125#issuecomment-2449481692) plz.
- [x] Important Stuff
  - [x] Make it aware of what tags should be applied to a given container image. 
- [x] Final Stuff
  - [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
  - [x] Code does not produce any clippy warnings `cargo clippy`
- [x] Ready for review.
- [x] Tested working.

## Useful resources
- <https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages>
- <https://dev.to/fabiancdng/automatic-deployment-using-docker-and-github-actions-16fb>
- <https://docs.docker.com/build/ci/github-actions/manage-tags-labels/>

### CODE REVIEW

**Comment by Snowiiii** [comment]
Like i said in https://github.com/Snowiiii/Pumpkin/issues/125#issuecomment-2449537924. I think using github would easier

**Comment by Snowiiii** [comment]
So how this was tested ?. I have no idea about github docker images. You could test the workflow on your Repo

**Comment by lokka30** [comment]
> So how this was tested ?. I have no idea about github docker images. You could test the workflow on your Repo

Package <https://github.com/lokka30/Pumpkin/pkgs/container/pumpkin>

Action <https://github.com/lokka30/Pumpkin/actions/runs/11752901407/job/32745104746>

Missing arm64 images so can't test the actual image generated myself.
Attestation would be nice (but difficult to get working)

**Comment by Snowiiii** [comment]
Does this require and Secrets i put into the Repo ?

**Comment by lokka30** [comment]
> Does this require and Secrets i put into the Repo ?

I didn't have to set up anything on my repo. The action did its work 😃 seems to all be handled automatically by GitHub.

Could you try `docker pull ghcr.io/lokka30/pumpkin:docker-deploy-test` and see if it works on your end, I don't have a amd64 system ready to test with

**Comment by Snowiiii** [comment]
> docker pull ghcr.io/lokka30/pumpkin:docker-deploy-test

So i pulled the image, How i execute it using docker?

**Comment by lokka30** [comment]
> > docker pull ghcr.io/lokka30/pumpkin:docker-deploy-test
> 
> So i pulled the image, How i execute it using docker?

Try `docker run -d ghcr.io/lokka30/pumpkin:docker-deploy-test`

**Comment by Snowiiii** [comment]
> > > docker pull ghcr.io/lokka30/pumpkin:docker-deploy-test
> > 
> > 
> > So i pulled the image, How i execute it using docker?
> 
> Try `docker run -d ghcr.io/lokka30/pumpkin:docker-deploy-test`

Looks like nothing happens
image

**Comment by lokka30** [comment]
is the container running in the background, @Snowiiii? try attach to it. or just delete the container and relaunch it without `-d` so it's attached

**Review by Yimura — APPROVED** [review]
IMO, this is already good start.

Later on we can push to support Docker Hub this will give people the option (as well improve visibility across different platforms).

### Todo List
These list items are my suggestions for the future, they don't need to be implemented in this PR right now!

- Support Docker Hub.
- Build a versioned release when a tag is published to the repository (ex. `snowiiii/pumpkin:1.21.3`)
- Build pull requests into docker containers, tag them as `snowiii/pumpkin:pr-214` for example (allows for spinning up quick tests servers to test behaviour or allow people to pull the tag that want to test without building).
- Build for different platforms (x86_64, arm64, etc...), docker buildx should be able to offer this functionality.

**Comment by lokka30** [comment]
great ideas @Yimura! @Snowiiii might be worth adding these ^^^ into the project to do list. also gentle bump about [this](https://github.com/Snowiiii/Pumpkin/pull/214#issuecomment-2473818165)

**Comment by Snowiiii** [comment]
Overall looks good.
Thanks @lokka30

**Pull request merged**
