### PR TITLE
Removed unused #[allow()]'s

### PR DESCRIPTION
**Pull request by DaniD3v**
title

### CODE REVIEW

**Comment by DaniD3v** [comment]
This only fails on the stable from githubs CI. Works on my nightly.
I think they patched the broken lint.

**Comment by Snowiiii** [comment]
1.81 is out. still failing

**Comment by DaniD3v** [comment]
I'm using the nightly toolchain so it might've been fixed in 1.82.
I'm just gonna remove the one case

I'll also replace the existing allows with expect.

**Comment by DaniD3v** [comment]
expect was newly added in `1.81` and warns if an `#[allow]` hint is not necessary anymore.

**Comment by Snowiiii** [comment]
Looks good. Thank you @DaniD3v

**Pull request merged**
