### PR TITLE
Pumpkin egui

### PR DESCRIPTION
**Pull request by suprohub**
## Description
A Detailed Description:
Pumkin server with gui for control process.
Gui can run on ios android web etc

## Testing
A description of the tests performed to verify the changes:
cargo run
pressing buttons start stop
joining to server

## Checklist
Things need to be done before this Pull Request can be merged.

- [ ] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [ ] Code does not produce any clippy warnings `cargo clippy`

## TODO
kill all processes after pressing stop button
no govnocode
fix bugs

### CODE REVIEW

**Comment by suprohub** [comment]
if we merge we can run it on android with beautiful gui

**Comment by suprohub** [comment]
this is bit wip

**Comment by suprohub** [comment]
any help? how kill all process?

**Comment by Snowiiii** [comment]
You can use `mActivityManager.killBackgroundProcesses(packageInfo.packageName);` for Java. For Rust you can just std::exit

**Comment by suprohub** [comment]
> You can use `mActivityManager.killBackgroundProcesses(packageInfo.packageName);` for Java. For Rust you can just std::exit

yes, but if i use std::exit egui app exit too. but i want to stop server killing all process without main

**Comment by suprohub** [comment]
@Snowiiii what do you think about this?

**Comment by suprohub** [comment]
we need custom logger implementation for egui, but now its looks cool and cun run on android

**Comment by DirefulBelt6803** [comment]
Have you run it on android yet?

**Comment by Snowiiii** [comment]
Hello @suprohub, First I recommend you to discuss bigger PR's on our discord. I mean it looks cool, but not really an good UI for Mobile devices

**Comment by suprohub** [comment]
And i try tomorrow implement custom pumpkin egui logger

**Comment by suprohub** [comment]
And fix filesystem erors

**Comment by DirefulBelt6803** [comment]
Flutter may be a better tool to use for the GUI, even though its not written in rust

**Comment by suprohub** [comment]
> Flutter may be a better tool to use for the GUI, even though its not written in rust

Poiepat

**Comment by suprohub** [comment]
O sorry i mean maybe

**Comment by suprohub** [comment]
But egui not what bad

**Comment by Snowiiii** [comment]
1. So looking at the screenshot, i wonder if the bottom half is the system keyboard  ?.
2. From the warns which say "read-only file-system", Im not sure but i may think we need to use the ndk bindings for the android fs

**Comment by suprohub** [comment]
Keyboard its egui bug as i know

**Comment by suprohub** [comment]
But i try fix it

**Comment by suprohub** [comment]
ok i try to resolve conficts and unmarked as draft

**Comment by suprohub** [comment]
Only two things to todo:
- [ ] fix keyboard
- [ ] fix custom icon loading

**Comment by suprohub** [comment]
I need help

**Comment by suprohub** [comment]
https://github.com/megadash452/ez-jni-rs?tab=readme-ov-file

**Comment by suprohub** [comment]
Ok i try this tomorow

**Comment by suprohub** [comment]
Its looks very cool and fresh

**Comment by suprohub** [comment]
> Its looks very cool and fresh

Its not works bruh

**Pull request closed without merging**
