### PR TITLE
Minify JSON assets to reduce binary size

### PR DESCRIPTION
**Pull request by PrintedScript**
## Description
The JSON files in the assets folder are not minified and is included in the binary, minifying them would reduce the binary size 

## Testing
Binary size decreased by almost 4MB

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings `cargo clippy`

### CODE REVIEW

**Comment by Snowiiii** [comment]
I was thinking of that. But not sure because this is much harder to debug

**Comment by PrintedScript** [comment]
> I was thinking of that. But not sure because this is much harder to debug

Maybe its possible to minify them at compile time instead?

**Comment by Snowiiii** [comment]
But i think it is a fine trait-off. This will reduce cloning size as well

**Comment by Snowiiii** [comment]
Btw thanks for not testing and writing "Binary size decreased by almost 4MB" in the testing section (this is not testing).
Because your changes did break the code

**Comment by Snowiiii** [comment]
https://github.com/Snowiiii/Pumpkin/commit/402f3951f57b2c887d44ceae00ba22aafcec2126 now at least fixed booleans. There are still problems when trying to send tag like `[minecraft:is_badlands, minecraft:is_jungle, minecraft:is_savanna]`
For now i recommend to just removing them from the `synced_registries.json`

**Comment by PrintedScript** [comment]
> Btw thanks for not testing and writing "Binary size decreased by almost 4MB" in the testing section (this is not testing). Because your changes did break the code

Sorry, I completely forgot to run the binary since I assumed that minifying the files would not affect anything. I am closing this PR in favour of #330

**Pull request closed without merging**
