### PR TITLE
Add shadow_color

### PR DESCRIPTION
**Pull request by Commandcracker**
## Description
Add shadow_color, new in 1.21.4

## Testing
image
image

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings: `cargo clippy`
- [ ] All unit tests pass: `cargo test`
- [ ] I added new unit tests, so other people don't accidentally break my code by changing other parts of the codebase. [How?](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)

### CODE REVIEW

**Review by Snowiiii — COMMENTED** [review]
I don't think you need to rename it

**Comment by Commandcracker** [comment]
> I don't think you need to rename it

You need to, because it is shadow_color and not shadowColor
see here
image
Mojang with insanity consistent naming conventions -_-

**Comment by Snowiiii** [comment]
Ah i though it just uses the field name, I didn't saw camelCase is used.

**Comment by Snowiiii** [comment]
Looks good then.
Thanks @Commandcracker

**Pull request merged**
