### PR TITLE
World persistence and .MCA region files

### PR DESCRIPTION
**Pull request by Asurar0**
Related to: https://github.com/Snowiiii/Pumpkin/issues/92

This pull request is intended to introduce a ChunkStorage actor, which will be responsible for retrieving and storing chunks to and from disk. The implementation of this feature is a crucial step towards achieving world persistence, a key requirement for Pumpkin to function as a vanilla server in the future.

Current state:
- [ ] Implement serialization of ChunkData (temporary at the moment)
- [x] Implement skeleton ChunkStorage trait 
- [x] Implement LMDB
- [ ] Implement .MCA storage
    - [ ] Implement Anvil format parsing

### CODE REVIEW

**Comment by Snowiiii** [comment]
> Could there perhaps be Linear region file format support planned?

Hey, What do you mean by Linear region file?. We definitly want to import and export Vanilla world files

**Comment by Bryntet** [comment]
That is really cool, I think we most definitely should support it.

**Comment by Snowiiii** [comment]
@Asurar0 any progress ?

**Comment by Snowiiii** [comment]
> Could there perhaps be Linear region file format support planned?

Now it's supported :D

**Pull request closed without merging**
