### PR TITLE
Add `block_id!` macro

### PR DESCRIPTION
**Pull request by lukas0008**
Added a macro which allows getting `BlockId` from blocks.json at compile-time.

Basic usage:
```rust
let grass_block = block_id!("minecraft:grass_block");
```

with block properties:
```rust
let button = block_id!(
    "minecraft:acacia_button",
    "facing" = "north",
    "powered" = "true",
    "face" = "floor"
);
```

### CODE REVIEW

**Comment by Snowiiii** [comment]
Hey, We need this for Chunks right?. Or for what usecases is this?

**Comment by Snowiiii** [comment]
Can't we refactor BlockId::new also use Compile time ?

**Comment by lukas0008** [comment]
but... how?

**Comment by StripedMonkey** [comment]
In principle it's possible to build the data as a bindgen-esque crate. I would advocate for not embedding block types/properties directly into the built binary though. Pre-generating them and caching the results somewhere feels like a better approach.

**Comment by lukas0008** [comment]
I do store the parsed blocks.json statically, in the same build it only has to be parsed once, so the compile length hit should be negligible, since each macro is literally just a hashmap lookup with a bit of logic to parse the input.

**Pull request merged**
