### PR TITLE
use derive macro for `Default` trait on `Scoreboard` struct and chunk optimizations

### PR DESCRIPTION
**Pull request by suprohub**
## Description
A Detailed Description:
when I was reading the code I accidentally came across this:
```rust
impl Default for Scoreboard {
    fn default() -> Self {
        Self::new()
    }
}
```
In my opinion, this is a useless piece of code, because we can use #[derive(Default)] instead of this, for speed up
code read time.

## Testing
`cargo run` and joining to server

## Checklist
Things need to be done before this Pull Request can be merged.

- [yes ] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [ yes] Code does not produce any clippy warnings `cargo clippy`

### CODE REVIEW

**Comment by Bryntet** [comment]
Change the commit name to something like "use derive macro for `Default` trait on `Scoreboard`"

**Comment by Snowiiii** [comment]
1. Use x instead of yes in checkboxes
2. Don't lie to me, Your Code does produce clippy warns

**Comment by Snowiiii** [comment]
I also just noticed you not only added derive Default for Scoreboard, You added a bunch of things. This should be split up into multiple PR's

**Comment by suprohub** [comment]
> I also just noticed you not only added derive Default for Scoreboard, You added a bunch of things. This should be split up into multiple PR's

how i can create another pull request? i can only view current

**Comment by Snowiiii** [comment]
> how i can create another pull request? i can only view current

You should use different branches

**Pull request closed without merging**
