### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by DirefulBelt6803**
## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings `cargo clippy`

### CODE REVIEW

**Comment by Snowiiii** [comment]
Im not sure about "Pumpkin only supports the latest version of Minecraft". Pumpkin does not instantly support the latest Minecraft version when it comes out, We still need some time porting over. Something like "Pumpkin aims to support the latest Minecraft version" would be better

**Comment by DirefulBelt6803** [comment]
Is there anything else?

**Comment by Snowiiii** [comment]
> Is there anything else?

Sorry that i don't mentioned it directly. But i also think you should better mention that ViaProxy is a tool/plugin which runs on a 3th party Proxy.

**Comment by Snowiiii** [comment]
Looks good now. 
Thanks @DirefulBelt6803

**Pull request merged**
