### PR TITLE
Implement level.dat reading and load the seed for use in world generation

### PR DESCRIPTION
**Pull request by neeleshpoli**
## Description
Adds support for reading the `level.dat` file in the anvil world format. With this support, the seed in the `level.dat` file is now used for chunk generation.

## Testing
Create a world in vanilla minecraft, and load the world into pumpkin. The newly generated chunks should seamlessly blend with the already generated chunks. A sample `level.dat` was added to unit tests for further testing.

## Checklist
Things need to be done before this Pull Request can be merged.
- [x] Implement `level.dat` loading
- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings: `cargo clippy`
- [x] All unit tests pass: `cargo test`
- [x] I added new unit tests, so other people don't accidentally break my code by changing other parts of the codebase. [How?](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)

### CODE REVIEW

**Comment by Snowiiii** [comment]
This should be placed not in the chunk dir.

**Comment by neeleshpoli** [comment]
I placed it in the chunk dir because this is specific thing to anvil world format; hence why it's in anvil file. Do you want me to separate the level.dat loading and chunk loading?

**Comment by Snowiiii** [comment]
I would like to separate chunk loading and "general world data loading". It would also make no sense to put it into the chunk folder since it has nothing to do with chunks. Also later someone can may use a different world format while having anvil chunks or the other way around

**Comment by Snowiiii** [comment]
Looks good now. It so impressive how well everything plays together now. Our generation exactly matches the vanilla. Still have to say great job @kralverde 
image
Thanks @neeleshpoli :+1:

**Pull request merged**
