### PR TITLE
Fix basic chat message packet

### PR DESCRIPTION
**Pull request by kralverde**
Fixes basic chat message packets.

### CODE REVIEW

**Comment by Snowiiii** [comment]
Hey, Im sure what was the problem?, Was it that is use 255 bytes instead of 256 ?

**Comment by kralverde** [comment]
it looks like the 256 and some optional types do not have a boolean in-front of them; they are conditional on other things

**Comment by Snowiiii** [comment]
So, It generally works now?

**Comment by kralverde** [comment]
For normal chat messages, yes

**Comment by Snowiiii** [comment]
Thanks so much. I really see the effort you put into this. Good job 👍

**Pull request merged**
