### PR TITLE
Disallow illegal characters in chat

### PR DESCRIPTION
**Pull request by Commandcracker**
## Description
This will disallow any illegal characters in chat.
It functions exactly the same as in the vanilla minecraft server, see net.minecraft.server.PlayerConnectiona(PacketPlayInChat packetplayinchat) net.minecraft.server.SharedConstants.isAllowedChatCharacter(char c0).

## Testing
I tested by running "MinecraftClient.getInstance().player.networkHandler.sendChatMessage" on the client with ANSI escape codes, disallowed Unicode and '§'.

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings `cargo clippy`

### CODE REVIEW

**Comment by Bryntet** [comment]
Why should these be disabled? Can we have config for this?

**Comment by Commandcracker** [comment]
> @Bryntet Why should these be disabled? Can we have config for this?

They should be disabled because they can't be displayed and normally typed. Some like § are used for color formatting. Allowing \n will make it, so any player can clear the whole chat. Allowing ANSI escape codes and other codes could lead to compromise, see [Weaponizing Plain Text: ANSI Escape Sequences as a Forensic Nightmare](https://www.youtube.com/watch?v=opW_Q7jvSbc)

**Comment by Bryntet** [comment]
> > @Bryntet Why should these be disabled? Can we have config for this?
> 
> They should be disabled because they can't be displayed and normally typed. Some like § are used for color formatting. Allowing \n will make it, so any player can clear the whole chat. Allowing ANSI escape codes and other codes could lead to compromise, see [Weaponizing Plain Text: ANSI Escape Sequences as a Forensic Nightmare](https://www.youtube.com/watch?v=opW_Q7jvSbc)
> 
> 

Fair.

**Comment by Commandcracker** [comment]
> @Snowiiii Looks like you are working with an Outdated Minecraft source. I recommend using Fabric. There is no `PlayerConnection` and no `SharedConstants.isAllowedChatCharacter`

Updated my sources:

net.minecraft.server.SharedConstants.isAllowedChatCharacter(char c0) -> net.minecraft.SharedConstants.isAllowedChatCharacter(char p_136189_)

net.minecraft.server.PlayerConnectiona(PacketPlayInChat packetplayinchat) ->
net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerboundChatPacket p_9841_)


**nothing changed!**

```java
public static boolean isAllowedChatCharacter(char p_136189_) {
    return p_136189_ != 167 && p_136189_ >= ' ' && p_136189_ != 127;
}
```

**Comment by Snowiiii** [comment]
> > @Snowiiii Looks like you are working with an Outdated Minecraft source. I recommend using Fabric. There is no `PlayerConnection` and no `SharedConstants.isAllowedChatCharacter`
> 
> Updated my sources:
> 
> net.minecraft.server.SharedConstants.isAllowedChatCharacter(char c0) -> net.minecraft.SharedConstants.isAllowedChatCharacter(char p_136189_)
> 
> net.minecraft.server.PlayerConnectiona(PacketPlayInChat packetplayinchat) -> net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerboundChatPacket p_9841_)
> 
> **nothing changed!**
> 
> ```java
> public static boolean isAllowedChatCharacter(char p_136189_) {
>     return p_136189_ != 167 && p_136189_ >= ' ' && p_136189_ != 127;
> }
> ```

Im pretty familiar with the Minecraft Code, And its pretty much looks like you still are using older sources than **1.21.3**.
`ServerGamePacketListenerImpl` was renamed to `ServerPlayNetworkHandler`. The Methods you provided do not existi

Here are my Sources:
```
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.16.9
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.108.0+1.21.3
``

**Comment by Snowiiii** [comment]
Looks like its now in `net.minecraft.util.StringHelper`

```java
 public static boolean isValidChar(char c) {
        return c != '\u00a7' && c >= ' ' && c != '\u007f';
}
```

**Comment by Snowiiii** [comment]
Anyways. It does make sense. LGTM
Thanks @Commandcracker

**Pull request merged**
