### PR TITLE
Spell Checker

### PR DESCRIPTION
**Pull request by StripedMonkey**
In taking a look at the project, there are a few typos in type names that potentially cause a lot of churn to fix. It's better to catch them now, than have to touch a thousand files later when `entitiy` is used in a hundred places.

Not trying to be a grammar nazi or anything in comments, but type names matter!

I've separated the spell corrections to different commits to minimize the number of files touched by each commit.

If you don't want to have a bunch of commits for spelling mistakes, make sure to commit and squash.

### CODE REVIEW

**Comment by Snowiiii** [comment]
Hey. Looks good. Thanks. I just writen coden too fast too often haha

**Comment by Snowiiii** [comment]
But you have to resolve the conflicts and fix the CI before i can merge

**Comment by StripedMonkey** [comment]
I will rebase when I'm home.

**Comment by Snowiiii** [comment]
Great. CI is passing now, Just fix the conflicts then again

**Comment by StripedMonkey** [comment]
If you're going to merge other PRs at 6AM my time, and I rebase at 6PM my time, this is going to go on for a while. Feel free to rebase yourself. It's not like these are complex changes.

**Comment by Snowiiii** [comment]
Is this ready for merge ?

**Comment by StripedMonkey** [comment]
I don't see why it wouldn't be. Go ahead when you're ready.

**Pull request merged**
