### PR TITLE
fix(player/abilities): only set `allow_flying` on Creative mode

### PR DESCRIPTION
**Pull request by DataM0del**
## Testing

- In Survival, press space bar 2 times and you should be falling / jumping.
- In Creative, press space bar 2 times and you should be flying.

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt` (a963bd727)
- [x] Code does not produce any clippy warnings `cargo clippy`

### CODE REVIEW

**Comment by Snowiiii** [comment]
Hey, @DataM0del is is currently only done for debugging purposes. If you want to could also just remove the abilities thing entirely.

**Comment by DataM0del** [comment]
Okay.

**Comment by DataM0del** [comment]
The linting is failing, will run `cargo fmt` and `cargo clippy` to see why.

**Comment by Snowiiii** [comment]
LGTM.
Should now also Fix: https://github.com/Snowiiii/Pumpkin/issues/278
Thanks @DataM0del

**Pull request merged**
