### PR TITLE
Added compile time BlockState

### PR DESCRIPTION
**Pull request by Alvsch**
## Description
Added `block_state!` macro for compile time `BlockState`

## Testing
Loading into a pre-generated minecraft world, moving around and generating new chunks

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings: `cargo clippy`
- [x] All unit tests pass: `cargo test`
- [ ] I added new unit tests, so other people don't accidentally break my code by changing other parts of the codebase. [How?](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)

### CODE REVIEW

**Comment by kralverde** [comment]
Do you think you can also add a static reference to state to block state and also add the block id to state?

**Comment by Snowiiii** [comment]
We now have duplicate code and also load the JSON twice which is a waste of RAM

**Comment by Alvsch** [comment]
> We now have duplicate code and also load the JSON twice which is a waste of RAM

I would like to fix that, but cyclic dependencies caused a bit of problems

**Comment by Snowiiii** [comment]
> > We now have duplicate code and also load the JSON twice which is a waste of RAM
> 
> I would like to fix that, but cyclic dependencies caused a bit of problems

Whats are the Problems?. Why you can't just remove it in pumpkin-world ?

**Comment by Alvsch** [comment]
> Whats are the Problems?. Why you can't just remove it in pumpkin-world ?

We can't remove it from pumpkin-world because some functions require it at runtime as the values aren't known at compile time, such as commands.

> > We now have duplicate code and also load the JSON twice which is a waste of RAM
> 
> I would like to fix that, but cyclic dependencies caused a bit of problems

I realized that pumpkin-macro's static variables are only compile time so what I said before is irrelevant

**Comment by kralverde** [comment]
> We now have duplicate code and also load the JSON twice which is a waste of RAM

No, in the macro the json is loaded at compile time.

**Comment by Snowiiii** [comment]
Also looks good and works.
Thanks @Alvsch :heart:

**Comment by Commandcracker** [comment]
Awesome 👍

**Pull request merged**
