### PR TITLE
adjust file descriptor limits

### PR DESCRIPTION
**Pull request by Bruce0203**

### CODE REVIEW

**Comment by Snowiiii** [comment]
Hey, Can you provide a description?

**Comment by Bruce0203** [comment]
The file descriptor is used to manage TCP sockets in the operating system. The number of file descriptors is limited per process, which can lead to a maximum limit of TCP sockets.

**Comment by Snowiiii** [comment]
Should'nt we let the user decide whats the File descriptors limit, I can imagine that common server distros change this value or unlimit it. I wonder how Netty/Vanilla Minecraft handles it

**Comment by lukas0008** [comment]
Correct me if I'm wrong, but isn't the soft limit of file handles on linux usually unlimited? Only the hard limit which cannot be changed by unprivileged users is usually set (although also usually to an unnecessarily high value like >=2048). But to change those, pumpkin would need to run as root, which is also against security practices. The soft limit being lower also would probably mean that the user themselves set it that way for a reason.

**Comment by Snowiiii** [comment]
Netty also uses the global OS value. I think we should use it aswell. There may will be useres who want to have an connection limit. I also don't really want to deal with libc. I will close this for now. Feel free to reopen or make an issue. To give good points to set the limits ourselfs

**Pull request closed without merging**
