### PR TITLE
Fix seed command output

### PR DESCRIPTION
**Pull request by kralverde**
## Description
Prints the seed as a i64 instead of a u64

## Testing
Ran /seed with a negative seed

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings: `cargo clippy`
- [x] All unit tests pass: `cargo test`

### CODE REVIEW

**Comment by Snowiiii** [comment]
I'm pretty sure that https://github.com/Snowiiii/Pumpkin/blob/cc0f30848ea597ef702558cb1e5fc57ed2a20372/pumpkin-world/src/world_gen/seed.rs#L4 should be also an i64 then

**Comment by kralverde** [comment]
> I'm pretty sure that https://github.com/Snowiiii/Pumpkin/blob/cc0f30848ea597ef702558cb1e5fc57ed2a20372/pumpkin-world/src/world_gen/seed.rs#L4 should be also an i64 then

No, internally our seed is a u64, it doesn't make sense for it to be signed. Converting from u64 to i64 is a no-op anyway because it has the same bits underneath

**Comment by Snowiiii** [comment]
> > I'm pretty sure that https://github.com/Snowiiii/Pumpkin/blob/cc0f30848ea597ef702558cb1e5fc57ed2a20372/pumpkin-world/src/world_gen/seed.rs#L4
> >  should be also an i64 then
> 
> No, internally our seed is a u64, it doesn't make sense for it to be signed. Converting from u64 to i64 is a no-op anyway because it has the same bits underneath

But why it should be unsigned ?. We may also want to use negative seeds internally, Or save them

**Comment by kralverde** [comment]
> > > I'm pretty sure that https://github.com/Snowiiii/Pumpkin/blob/cc0f30848ea597ef702558cb1e5fc57ed2a20372/pumpkin-world/src/world_gen/seed.rs#L4
> 
> > >  should be also an i64 then
> 
> > 
> 
> > No, internally our seed is a u64, it doesn't make sense for it to be signed. Converting from u64 to i64 is a no-op anyway because it has the same bits underneath
> 
> 
> 
> But why it should be unsigned ?. We may also want to use negative seeds internally, Or save them

IMO It doesn't make sense to me conceptually for it to be signed. There's not concept of positive or negative for what is effectively a bit string for our RNG. I think having it signed was a limitation of Java.

We can always add a serialize method to the seed struct for writing and stuff to do to no-op `as i64` to minimize confusion.

**Comment by Snowiiii** [comment]
Mhh Okay.
I also wonder if https://github.com/Snowiiii/Pumpkin/blob/9b184f73b99c6b7b97cf4ee0fe08be84d497b33a/pumpkin-config/src/lib.rs#L70 could may be a i64 directly so we don't have to parse it from a String

**Comment by kralverde** [comment]
> Mhh Okay.
> 
> I also wonder if https://github.com/Snowiiii/Pumpkin/blob/9b184f73b99c6b7b97cf4ee0fe08be84d497b33a/pumpkin-config/src/lib.rs#L70 could may be a i64 directly so we don't have to parse it from a String

Users can input strings as seeds tho

**Comment by Snowiiii** [comment]
> > Mhh Okay.
> > I also wonder if https://github.com/Snowiiii/Pumpkin/blob/9b184f73b99c6b7b97cf4ee0fe08be84d497b33a/pumpkin-config/src/lib.rs#L70
> >  could may be a i64 directly so we don't have to parse it from a String
> 
> Users can input strings as seeds tho

I'm not sure what you mean, a seed is always a number isn't it ?

**Comment by kralverde** [comment]
> > > Mhh Okay.
> 
> > > I also wonder if https://github.com/Snowiiii/Pumpkin/blob/9b184f73b99c6b7b97cf4ee0fe08be84d497b33a/pumpkin-config/src/lib.rs#L70
> 
> > >  could may be a i64 directly so we don't have to parse it from a String
> 
> > 
> 
> > Users can input strings as seeds tho
> 
> 
> 
> I'm not sure what you mean, a seed is always a number isn't it ?, If you mean to just using " ", this isn't really an argument for me, I think its nicer to just force the user to put a raw number instead of using a String and then parsing is back into a number

But like, you can have a string be the seed and it gets hashed into a numerical value. So you are right in that they are ultimately numbers, but if you go into Minecraft you can type a sentence into the set seed and it will work.

**Comment by Snowiiii** [comment]
Overall looks good.
Thanks @kralverde

**Pull request merged**
