### PR TITLE
feat: initial docker support

### PR DESCRIPTION
**Pull request by Erb3**
Adds support for docker

- [x] Compile in docker
- [x] Load favicon
- [x] Document usage
- [x] Fix log spam
- [x] Make SIGTERM work
- [x] Alpine

I've decided that GitHub actions can be done later. Since we aren't making releases yet, it's hard to publish docker images.

### CODE REVIEW

**Comment by Snowiiii** [comment]
We want to give people the option to choose their own icons. So compiling with Pumpkin's icon data is not an option

**Comment by Erb3** [comment]
Well in the case we can't have a default icon. I am not suggesting to hardcode it, but we can't both have a default loaded dynamically, and be able to compile to a binary

**Comment by Snowiiii** [comment]
So im not very fimiliar with docker, Why it isn't possible or so easy to just use the icon file directly?

**Comment by Erb3** [comment]
It's not a docker limitation, we totally could include the icon, but:

1. You can't just give the binary to someone, and say "run this". It will panic due to the missing icon. This is unrelated to Docker.
2. It uses `CARGO_MANIFEST_DIR` to find the icon, which is injected by cargo.

Again, neither of these are limitations of Docker. I could set the `CARGO_MANIFEST_DIR` myself, but it feels jank. I also think that being able to run Pumpkin standalone would be a benefit. It would be like you running `java -jar paper.jar`, but it crashes because you didn't include a default icon.

**Comment by Snowiiii** [comment]
Your right, I made the icon optional so you can start the server with only the executable
https://github.com/Snowiiii/Pumpkin/commit/b37039126ac1e5a4c1c0e104f78923e3b3c5f4f9

**Comment by Snowiiii** [comment]
> It now loads successfully, however now the console is being spammed by the following log:
> 
> ```
> 2024-08-21T15:56:27.941Z INFO  [pumpkin::commands] Text { text: "Empty Command" }
> ```

Does it spamm?. Or only says when sending something in the terminal?

**Comment by Erb3** [comment]
It spams

> > It now loads successfully, however now the console is being spammed by the following log:
> > ```
> > 2024-08-21T15:56:27.941Z INFO  [pumpkin::commands] Text { text: "Empty Command" }
> > ```
> 
> Does it spamm?. Or only says when sending something in the terminal?

Spam, many each ms

**Comment by Snowiiii** [comment]
> > > It now loads successfully, however now the console is being spammed by the following log:
> > > ```
> > > 2024-08-21T15:56:27.941Z INFO  [pumpkin::commands] Text { text: "Empty Command" }
> > > ```
> > 
> > 
> > Does it spamm?. Or only says when sending something in the terminal?
> 
> Spam, many each ms

Can you may apply this patch and test ?

[test.patch](https://github.com/user-attachments/files/16695118/test.patch)

**Comment by Snowiiii** [comment]
> > > > It now loads successfully, however now the console is being spammed by the following log:
> > > > ```
> > > > 2024-08-21T15:56:27.941Z INFO  [pumpkin::commands] Text { text: "Empty Command" }
> > > > ```
> > > 
> > > 
> > > Does it spamm?. Or only says when sending something in the terminal?
> > 
> > 
> > Spam, many each ms
> 
> Can you may apply this patch and test ?

[test.patch](https://github.com/user-attachments/files/16695134/test.patch)

**Comment by Erb3** [comment]
Your .patch file didn't work, perhaps CRLF/LF? Well I manually did the change and it worked :)

**Comment by Snowiiii** [comment]
Great, So whats needs to be fixed next?

**Comment by Erb3** [comment]
> Great, So whats needs to be fixed next?

The biggest problem now is termination not working, for some reason. This leads to the docker container being slow to stop (10s timeout)

**Comment by Erb3** [comment]
It suspect this is caused by running pumpkin with PID 1, which can't terminate like normal. You have to install a special CTRL+C handler, similar to what is used for graceful shutdown. See https://robertying.com/post/sigterm-docker/

**Comment by Snowiiii** [comment]
@Erb3 Can you may test with latest commit ?

https://github.com/Snowiiii/Pumpkin/commit/fa1ca0782e3f6418706e66ca3137da4b5f90a0f9

**Comment by Erb3** [comment]
> @Erb3 Can you may test with latest commit ?
> 
> [fa1ca07](https://github.com/Snowiiii/Pumpkin/commit/fa1ca0782e3f6418706e66ca3137da4b5f90a0f9)

Works like a charm!

**Comment by Snowiiii** [comment]
Okay, Whats next ?

**Comment by Erb3** [comment]
I've decided to post-pone GitHub actions to publish, since we aren't making releases. I'll try to get it working on alpine, since it has a smaller footprint. If that doesn't work, we're ready to merge :)

**Comment by Snowiiii** [comment]
Looks good. I just wonder if it makes sense to may use `RUSTFLAGS="-C target-cpu=native"` ?

**Comment by Snowiiii** [comment]
Thank you @Erb3

**Pull request merged**
